/* ORG INFO */
export const GET_ORG_INFO = "GET_ORG_INFO"
export const GET_ORG_INFO_SUCCESS = "GET_ORG_INFO_SUCCESS"
export const GET_ORG_INFO_FAIL = "GET_ORG_INFO_FAIL"

/* REPO LIST */
export const GET_REPO_LIST = "GET_REPO_LIST"
export const GET_REPO_LIST_SUCCESS = "GET_REPO_LIST_SUCCESS"
export const GET_REPO_LIST_FAIL = "GET_REPO_LIST_FAIL"

/* COMMIT LIST */
export const GET_COMMIT_LIST = "GET_COMMIT_LIST"
export const GET_COMMIT_LIST_SUCCESS = "GET_COMMIT_LIST_SUCCESS"
export const GET_COMMIT_LIST_FAIL = "GET_COMMIT_LIST_FAIL"

/* ORG MEMBERS */
export const GET_ORG_MEMBERS = "GET_ORG_MEMBERS"
export const GET_ORG_MEMBERS_SUCCESS = "GET_ORG_MEMBERS_SUCCESS"
export const GET_ORG_MEMBERS_FAIL = "GET_ORG_MEMBERS_FAIL"
